name: sentiment-analysis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - numpy=1.23.5
  - pandas=1.5.2
  - matplotlib=3.6.2
  - seaborn=0.12.1
  - scikit-learn=1.2.0
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - cudatoolkit=11.7
  - nltk=3.8.1
  - tqdm=4.64.1
  - jupyter=1.0.0
  - pip:
    - pyspellchecker==0.8.2
    - symspellpy==6.7.7
    - tensorboard==2.11.2
    - transformers==4.30.2
    - wget==3.2
    - mlflow==2.4.1
    - optuna==3.2.0
    - shap==0.41.0 